### ISSUE TITLE
[Bug] Dependencies missing for debian 10 and ubuntu 20.04

### ISSUE THREAD

**Issue by abejaranoh** [goastian/midori-desktop#16]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

when installing on Debian 10 (buster) I get this error:

root@479742c3b00c:/home/test# apt install ./midori_11.0.0_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'midori' instead of './midori_11.0.0_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 midori : Depends: libffi8 but it is not installable
          Depends: libgcc-s1 but it is not installable
          Depends: libgdk-pixbuf-2.0-0 but it is not installable
          Depends: libvpx7 but it is not installable
E: Unable to correct problems, you have held broken packages.

versions older than ubuntu 22.04 and debian 12 (bookworm) might have the same issue since the package libffi8 is only available from these versions

https://packages.debian.org/bookworm/libffi8
https://packages.ubuntu.com/jammy/libffi8

there is a package
https://packages.debian.org/bullseye/libffi7   --> only debian 11
https://packages.debian.org/buster/libffi6     --> only debian 10
https://packages.ubuntu.com/focal/libffi7      --> ubuntu 20.04 and 22.04 

maybe using the package depending on the version of the OS might be a solution. 

I did not check the other packages

### To Reproduce

Debian 10
-  run debian 10 (docker run -ti debian:10 /bin/bash)
- apt update (if required)
- apt install wget (if required)
- wget https://github.com/goastian/midori-desktop/releases/download/v11.0.0/midori_11.0.0_amd64.deb
- apt install ./midori_11.0.0_amd64.deb

Ubuntu 20.04 (focal)
- run ubuntu 20.04 (docker run -ti ubuntu:20 /bin/bash)
- apt update (if required)
- apt install wget (if required)
- wget https://github.com/goastian/midori-desktop/releases/download/v11.0.0/midori_11.0.0_amd64.deb
- apt install ./midori_11.0.0_amd64.deb

### Expected behavior

package is installed

### OS Info

Debian 10 (buster); Ubuntu 20.04

### Midori Version

11.0.0

**Comment by Ponchale** [comment]
This bug was solved in version 11.0.1, it was in the process of building the package which included updated libraries that were not found in previous versions of the operating system.

**Comment by Ponchale** [comment]
Issue resolved in version 11.1.0
