### ISSUE TITLE
Mozilla extensions search redirects to japanese app store

### ISSUE THREAD

**Issue by metamaterialsuit** [goastian/midori-desktop#28]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Searching for an extension in settings takes the user to the japanese version of then mozilla app store

### To Reproduce

Go to settings -> extensions and search for an extension 
A new tab will open in the japanese app store.

### Expected behavior

My expectation is that it would take the user to the region specific app store 

### OS Info

Ubuntu 22.10

### Midori Version

11

**Comment by mriliu** [comment]
I misspoke, the OS in question is lubuntu not ubuntu

**Comment by Ponchale** [comment]
Thank you for reporting these incidents, the Midori build process was already finished and although the tag was created a few minutes ago the distribution process was already finished, we promise to fix this in the next version Midori 11.1.1.

Thank you.

**Comment by Ponchale** [comment]
fix problem change to url general
