### ISSUE TITLE
[Bug] No shortcut seems to toggle the state of the sidebar 

### ISSUE THREAD

**Issue by metamaterialsuit** [goastian/midori-desktop#29]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I believe that a shortcut option exists to toggle the visibility of the sidebar. I've tried a few candidates but none have done so.

### To Reproduce

Create a keyboard shortcut for one of the options pertaining to the sidebar visibility.

### Expected behavior

I should be able to hide or show the sidebar 

### OS Info

Ubuntu 22.10

### Midori Version

11

**Comment by mriliu** [comment]
Im sorry, I forgot that the computer in question is actually running lubuntu, not ubuntu

**Comment by Ponchale** [comment]
Thank you for reporting these incidents, the Midori build process was already finished and although the tag was created a few minutes ago the distribution process was already finished, we promise to fix this in the next version Midori 11.1.1.

Thank you.

**Comment by Ponchale** [comment]
@mriliu To activate the original Midori shortcuts you have to disable the Firefox shortcuts so that all custom shortcuts are successfully activated.

**Comment by Ponchale** [comment]
fix problem
