### ISSUE TITLE
[Bug] deleted.

### ISSUE THREAD

**Issue by dacomboman** [goastian/midori-desktop#31]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Think the title of this report says it all.

### To Reproduce

Tools - Settings - Browser manager sidebar  - 

### Expected behavior

Show autohide options.

### Screenshots

https://snipboard.io/7suCPa.jpg

### OS Info

Windows 11

### Midori Version

11.1.0

**Comment by dacomboman** [comment]
Just tested on SpiralLinux and have same outcome.

**Comment by Ponchale** [comment]
@dacomboman I don't understand what you mean, can you please explain?
