### ISSUE TITLE
[Bug] [Atutomatically hide Toolbar] works too sensitively

### ISSUE THREAD

**Issue by sdsucks** [goastian/midori-desktop#33]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

unhiding the toolbar is activated about 30 pixels below the top of the screen.

i can't even click buttons or menus of some sites which are located on top of the screen.

### To Reproduce

Settings > Design > Firefox Photon・Lepton UI > Lepton Settings > Atutomatically hide Toolbar

### Expected behavior

usually you have to move your mouse to the very top of the screen to unhide the toolbar

### OS Info

win10 x64

### Midori Version

11.1.0

**Comment by Ponchale** [comment]
Hello, after the test we found the options executing normally but we will continue testing.

**Comment by Ponchale** [comment]
Solved the problem
