### ISSUE TITLE
[Bug] Midori installer being stop by Windows Security

### ISSUE THREAD

**Issue by vietbunasd** [goastian/midori-desktop#39]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When start the installer, it will be stopped by Windows Security for being an unrecognized app

### To Reproduce

1. Turn on Windows Security
2. Download the installer
3. Try to install the browser
4. Being stop by Windows Security

### Expected behavior

Can install the browser without being stopped by Windows Security

### Screenshots

![Capture](https://github.com/goastian/midori-desktop/assets/44780347/67315ba0-80fd-4432-afcb-11d1e5d5ae9f)

### OS Info

Windows 10

### Midori Version

11.1.1

**Comment by Ponchale** [comment]
Thanks for the report, it's not that it's a security problem, it's more of a problem with the Windows developer license (we don't have it yet) to skip that notice it's very easy to right click on the file and say unlock and that's it. It doesn't appear again.
