### ISSUE TITLE
[Bug] Midori installer doesn't install the right version

### ISSUE THREAD

**Issue by vietbunasd** [goastian/midori-desktop#42]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The midori 11.1.3 installer doesn't upgrade midori from 11.1.2 and browser self upgrade can't find the newest update version 11.1.3

### To Reproduce

1. Download Midori installer both online and offline version from astian.org and GitHub
2. Install it
3. Midori version still the same after update(11.1.2)
4. In about midori update, it's still said midori in the latest version(11.1.2)

### Expected behavior

Install and update Midori browser to latest version(11.1.3)

### OS Info

Windows 10 Pro 22H2

### Midori Version

11.1.2

**Comment by Ponchale** [comment]
Thanks, it is something that we will fix in the next version and it only affects Windows. Thank you.

**Comment by ioc2e3** [comment]
> 版

Just to ask ...

What is the reason for this problem?

...........................

Why is there a problem with the Windows version?

.

**Comment by ioc2e3** [comment]
> 謝謝，我們將在下一版本中修復此問題，並且僅影響 Windows。謝謝。

Just to ask ...

What is the reason for this problem?

......................................

Why is there a problem with the Windows version?

.
