### ISSUE TITLE
[Bug] Issue with Spoof User Agent option and user.js options

### ISSUE THREAD

**Issue by MuerteRoja** [goastian/midori-desktop#44]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Hello, good afternoon, my name is Facundo, I recently installed the Midori web browser to test it, and I have seen that it has some errors, the options to fake the user agent do not work (I show it in the video) as well as the user.js options do not work either (in the video I also show it) likewise I ask to completely ignore the user interface, I applied a CSS theme called floorp one which was created by the user Godiesc on Github, I did this in the particular thing so that my user interface looked aesthetically more beautiful, essentially I wanted to make known these 2 problems that have arisen in the browser, the one of user agent forgery and the other of user.js on my own account I have forced to look for the arkenfox user.js file and apply it to Midori so that it has some kind of protection

### To Reproduce

Go to Spoof User Agent options in the general tab, select any user agent, and go to a web page like deviceinfo.me where it tells you what your user agent is
Go to performance options in the general tab, go to user.js options, select any user agent, go to the profile folder you are using, open it in file explorer, open the user.js file and check that it doesn't say anything like: "404 Error Not Found"

### Expected behavior

It is expected that the Spoof User Agent options will work and the user agent can actually be spoofed, it is expected that the user.js list will be updated (because the ones that currently exist have been deleted from the official repository a long time ago)

### Screenshots

https://github.com/goastian/midori-desktop/assets/126993006/edc63d52-01a0-4417-8e7f-00ce1a3fbff2

### OS Info

Windows 11 Professional 23H2

### Midori Version

11.2 (64-bit)

### Additional context

I wanted to record a video of all this, since I particularly consider that it has more value than a simple screenshot

**Comment by Ponchale** [comment]
Thanks for the report, if it seems that the bug only affects Windows, we will be working on the next update to improve this incident.

**Comment by MuerteRoja** [comment]
Okey

**Comment by MuerteRoja** [comment]
> Thanks for the report, if it seems that the bug only affects Windows, we will be working on the next update to improve this incident.

By the way, sorry I forgot to ask before, what do you have to comment about what you showed in the video with the user.js option?

**Comment by Ponchale** [comment]
Fixed advanced preferences problem

**Comment by ioc2e3** [comment]
that ...

What is the cause of this error?

.

**Comment by Ponchale** [comment]
> that ...
> 
> What is the cause of this error?
> 
> .

Download resources were not available and download links were changed.
