### ISSUE TITLE
[Bug] My computer's antivirus detects the Midori web browser as a trojan

### ISSUE THREAD

**Issue by MuerteRoja** [goastian/midori-desktop#46]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Hello, good evening, I am currently using the Kaspersky Total Security antivirus and said antivirus detects the Midori web browser as a generic trojan. I have had to add the program to the list of exclusions so that the antivirus does not eliminate it, can anyone do you know why this happens?

### To Reproduce

Install Kaspersky Total Security antivirus, in the settings choose maximum protection

### Expected behavior

That the antivirus does not detect my web browser as a trojan

### Screenshots

![Captura de pantalla 2023-12-20 000432](https://github.com/goastian/midori-desktop/assets/126993006/b15e68cf-9a1e-4d39-99d0-6afefc1ab001)

### OS Info

Windows 11 Professional 23H2

### Midori Version

11.2 (64-bit)

**Comment by Ponchale** [comment]
> ### Attention!
> 
>     * [x]  I undertand that Midori is NOT supported on Windows 7/8.1 or lower.
> 
> 
> ### Describe the bug
> 
> Hello, good evening, I am currently using the Kaspersky Total Security antivirus and said antivirus detects the Midori web browser as a generic trojan. I have had to add the program to the list of exclusions so that the antivirus does not eliminate it, can anyone do you know why this happens?
> ### To Reproduce
> 
> Install Kaspersky Total Security antivirus, in the settings choose maximum protection
> ### Expected behavior
> 
> That the antivirus does not detect my web browser as a trojan
> ### Screenshots
> 
> ![Captura de pantalla 2023-12-20 000432](https://private-user-images.githubusercontent.com/126993006/291743403-b15e68cf-9a1e-4d39-99d0-6afefc1ab001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzIzMjksIm5iZiI6MTcwMzAzMjAyOSwicGF0aCI6Ii8xMjY5OTMwMDYvMjkxNzQzNDAzLWIxNWU2OGNmLTlhMWUtNGQzOS05OWQwLTZhZmVmYzFhYjAwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwMDI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWMzMDVlMjk0ZjlhODk0NDNlNGYxN2Q2YzFjZjcyOTg1NWVkOGM0MmU3NGI4OWMwOGEyNDEwZWNlNDdlYTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CW_f4NMlIgIfoB_IxFdPNuqTavh3YUrg26Cinqw9WXs)
> ### OS Info
> 
> Windows 11 Professional 23H2
> ### Midori Version
> 
> 11.2 (64-bit)
> ### Additional context
> 
> _No response_

This is clearly a false positive on the part of Kaspersky

since there are multiple reports

https://midori.en.lo4d.com/virus-malware-tests

https://www.virustotal.com/gui/file/58dc39c8f729e80040f25d4f2cc9850cf597afc733736c42047a90a3ceec5a9f/detection
