### ISSUE TITLE
[Bug] Problems with hyperlinks on the Midori official website

### ISSUE THREAD

**Issue by MuerteRoja** [goastian/midori-desktop#49]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I access the official website of the Midori web browser and I want to view the "About US" section in Spanish, I cannot do so. Additionally, when I click on the "About US" button at the top I am redirected to the home page, in order to go to the "About US" section I am forced to scroll down completely and click on the "About US" at the bottom since the one at the top does not work well

### To Reproduce

Click on the button to change language to Spanish located at the top right, then click on "About US" at the top of the page in the center, you will see that this hyperlink does not work correctly, since you are redirected to the home page, scroll down all the way and click on "About US" below to access said section, you will see that you cannot view it in Spanish

### Expected behavior

The expected behavior is that the "About US" button at the top in the center works without redirecting you to the home page, without having to scroll down completely to access the "About US" section. Another expected behavior is be able to view the "About US" section in Spanish

### Screenshots

https://github.com/goastian/midori-desktop/assets/126993006/94fecd1d-fa31-4973-aee9-736e86b13409

### OS Info

Windows 11 Professional 23H2

### Midori Version

11.2 (64-bit)

### Additional context

Just in case I will also write this Issue in the repository called: "general-discussion-suite" since I am not very clear in which of the two repositories to report this issue, I will report it in both

**Comment by Ponchale** [comment]
This is part of Astian you can send the report to contact@astian.org this is for the development of Midori, But we appreciate the report
