### ISSUE TITLE
 Can not change display language

### ISSUE THREAD

**Issue by zcg** [goastian/midori-desktop#58]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I want to change display language from en to zh-cn china
but display en and never change

### To Reproduce

1. go to settings -> general -> change display language
2. change to 简体中文 zh-cn
3. restart

### Expected behavior

change to display zh-cn

### OS Info

windows11

### Midori Version

11.2.2 (64-bit)

**Comment by Ponchale** [comment]
We offer an apology this is a problem present in this version which will be corrected at 11.2.3 that is about to leave in the next days.

Thanks for understanding and patience.

**Comment by ioc2e3** [comment]
> 我們深表歉意，這是此版本中存在的問題，該問題將在未來幾天即將發布的 11.2.3 中得到修正。
> 
> 感謝您的理解和耐心。

Just to ask ...

What is the reason for this problem?

...........................

Why is there a problem with the Windows version?

.
