### ISSUE TITLE
[Bug] The files in PDF format that I want to view in the web browser are automatically downloaded involuntarily to the temp folder on my computer

### ISSUE THREAD

**Issue by MuerteRoja** [goastian/midori-desktop#61]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Good afternoon, when I access a file in PDF format, at the time of accessing said file it is automatically downloaded to the Temp folder, I would like to know if I do not have an option that is responsible for preventing this, or failing that , some option which is responsible for deleting all temporary files when closing the browser

### To Reproduce

1 Access the web platform of your work or study environment
2 Select a PDF file which you want to view in the PDF viewer
3 You will be able to see how this file is automatically downloaded involuntarily to the Temp folder on your computer

### Expected behavior

Normally view the files in PDF format without them being downloaded to the Temp folder on my computer or have an option that is responsible for deleting all the temporary files downloaded when closing the web browser

### Screenshots

![Descargas automáticas](https://github.com/goastian/midori-desktop/assets/126993006/37c5e47d-ac52-4bde-8578-72e64a51f8a3)

### OS Info

Windows 11 Professional 23H2

### Midori Version

11.2.2 (64-bit)

**Comment by Dan-cer** [comment]
I can't confirm this on Win 10.0. I chosed a manual for my smartphone with a download link. When clicked on the download button, the pdf opens immediately in browser tab as it should.
Could it be an issue only on Win 11?

**Comment by MuerteRoja** [comment]
> I can't confirm this on Win 10.0. I chosed a manual for my smartphone with a download link. When clicked on the download button, the pdf opens immediately in browser tab as it should. Could it be an issue only on Win 11?

Yeah, maybe

**Comment by Ponchale** [comment]
We are working and in the next update it will be solved

**Comment by Ponchale** [comment]
fix #efc193b
