### ISSUE TITLE
Can't set other language than english[Bug] 

### ISSUE THREAD

**Issue by Dan-cer** [goastian/midori-desktop#62]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

After having installed Midori from official website (and later also from Uptodown.com) on Windows 10 64bit, the whole interface remains in english language. I tried several times to set it to german or italian or french, without any change.
Same browser installed in Linux Mint immediately is displayed in german, without having to change it from english to german.
In the uninstall procedure on Windows I found it is an en-us version. 
However, nowwhere I can get a german version (for Windows) when downloading.

### To Reproduce

1. Open settings 
2. Click on "General"
3. Scroll to "Language"
4. Set "German" 
5. Restart browser
6. Still english interface

### Expected behavior

At least after restart it should be a german interface.

### OS Info

Windows 10.0 built 19045

### Midori Version

11.2.2 64bit

### Additional context

nothing to add

**Comment by Dan-cer** [comment]
I found out that files in the folder "omni.ja_FILES/chrome/de/locale/de/" contain german translations in Linux, but not in Windows.

**Comment by Ponchale** [comment]
Thanks for the report, the next version will be corrected

**Comment by Dan-cer** [comment]
As the new release isn't published yet I want to add that in the Linux version there are quit a few items not yet translated in german but still in english.
Do you need help to translate them? I could offer you to do it. You might have a table where I could fill in the missing terms?
I have such in my wordpress blog plugin "loco translate".

**Comment by ioc2e3** [comment]
> 感謝修改檢舉，下個版本會

that ...

Folder ( omni.ja_FILES/chrome/de/locale/de/ ) ← Why does the version use on Windows not have ...

.

**Comment by Ponchale** [comment]
We have released Midori 11.3 and the multilanguage option is now available in all operating systems,

**Comment by ioc2e3** [comment]
> 我們發布了 Midori 11.3，多語言選項現已在所有作業系統中提供，

But ...

Traditional Chinese interface is not completely traditional Chinese ...

.

**Comment by Ponchale** [comment]
> > 我們發布了 Midori 11.3，多語言選項現已在所有作業系統中提供，
> 
> But ...
> 
> Traditional Chinese interface is not completely traditional Chinese ...
> 
> .

Thank you for your report friend, we are improving the entire issue of translations step by step, and with each update we will be improving even more.
