### ISSUE TITLE
Workspaces are not persistent[Bug] 

### ISSUE THREAD

**Issue by Dan-cer** [goastian/midori-desktop#63]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I added 2 more workspaces, shopping and media to the existing standard workspace.
Next time after restart both 2 added workspaces are gone.

### To Reproduce

1. Click on + in sidebar to add a workspace
2. I named it "shopping"
3. I selected an icon ('shopping')
4. I rightclicked on the new icon and selected "Manage this workspace"
5. I selected a container tab (shopping)
6. I restarted browser
7. New workspace icon is gone, only standard is visible.

### Expected behavior

Adding or creating any new workspace should persist with an option to edit or delete.

### OS Info

Win 10.0 built 19045

### Midori Version

11.2.2 64bit

**Comment by Ponchale** [comment]
fix bug #efc193b50a983cd03a6b383525b29e5734be8de5

**Comment by francjp** [comment]
Still happening, now on Version 11.3.3, in Linux (version from tar.bz2 64)

Created a new profile, added a new (one or more, this is independent), choosing containers or leaving all by default (not even renaming the workspaces), and once the browser restarts, all the workspaces created are gone.

This is not happening on version 11.3.2 (from AUR repositories).
