### ISSUE TITLE
[Bug] User.js settings are not applied to me in my browser

### ISSUE THREAD

**Issue by MuerteRoja** [goastian/midori-desktop#64]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Hello, good evening, when I try to apply the Yokoffing Securefox options in the user.js file, an error called "error 404" appears, and it directly does not allow me to apply these options. I have recorded the video in which I show the incident that occurred today 03/26/2024 that is, this bug is current, not old, I would like some developer solve this error if possible (In fact I also remember that I also had this incident in the past and made an issue about it https://github.com/goastian/midori-desktop/issues/44 )

### To Reproduce

Go to Settings
General
Performance
user.js Settings
SecureFox
Apply
Cancel backup of the file, current user.js, overwrite the file directly with the new options

### Expected behavior

Being able to apply the Yokoffing Securefox options without problems

### Screenshots

https://github.com/goastian/midori-desktop/assets/126993006/15a29fdf-9d6e-48b3-8f52-f1c5ada8126a

### OS Info

Windows 11 Pro 23H2

### Midori Version

11.2.1 (64-bit)

**Comment by Ponchale** [comment]
This has been fixed since version 11.3.0 but in testing it did not show any problems.
