### ISSUE TITLE
[Bug] Spoof user agent options not working

### ISSUE THREAD

**Issue by MuerteRoja** [goastian/midori-desktop#65]
### Attention!

- [X] I undertand that Midori is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Video recorded today 27/03/2024 in the web browser options, I try to spoof my user agent and, however, these options do not work for me

### To Reproduce

Go to Settings
General
User Agent
Select any of the user agent options
Go to deviceinfo.me/ on this web page you can see that the configurations have not been applied

### Expected behavior

The expected behavior in the Browser section of deviceinfo.me appears that I am using any of the other previously selected user agents instead of Firefox

### Screenshots

https://github.com/goastian/midori-desktop/assets/126993006/636b93d3-ca6d-4db4-a150-f47afef3b533

### OS Info

Windows 11 Pro 23H2

### Midori Version

11.2.1 (64-bit)

**Comment by ioc2e3** [comment]
Excuse me ...

Why ( spoof user agent ) option don't work ?

.

**Comment by Ponchale** [comment]
We have released Midori 11.3 and in all our tests it appears that this possible error is solved, I say possible error because we were unable to confirm it in the multiple tests carried out.
