### ISSUE TITLE
[Bug]: Web browser player is invalid

### ISSUE THREAD

**Issue by MuerteRoja** [goastian/midori-desktop#71]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Hello, good morning, I am currently using invidio.io artificial intelligence to create videos, and when I finish creating the video a banner appears telling me that the browser's video player is not valid.

### Reproduction Steps

Go to the invideo.io website
Go to the generate text to video section
Create a video from prompts
You will be able to see that once the process is finished, the sign appears that the browser's video player is not valid.

### Expected Behavior

The expected behavior is that the previously mentioned sign does not appear, that the web browser video player is not valid and so I can view the video that I have created with artificial intelligence

### Actual Behavior

The aforementioned poster appears preventing me from seeing the video I created

### Screenshots

https://github.com/goastian/midori-desktop/assets/126993006/d0408721-7898-4fb9-874f-7489297138a9

### Browser Version

11.3.0 (64-bit)

### Operating System

Windows 11 Pro 23H2

**Comment by Ponchale** [comment]
There are sites and platforms that are exclusively for Chrome or Edge chromium browsers, while support is resolved and extended to new formats and new technologies, you can change the user agent and without leaving Firefox you can emulate Midori as if you were in Chrome.
