### ISSUE TITLE
[Bug]: Spoof user agent option still not working

### ISSUE THREAD

**Issue by MuerteRoja** [goastian/midori-desktop#72]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Video recorded today 04/08/2024, in the same video I show that I am using version 11.3.0 (64-bit) of the Midori web browser, due to the previously open forum https://github.com/goastian/midori-desktop/issues/71 on Ponchale's recommendation I have used the spoof option the browser's user agent, however, is still not working, when I go to the deviceinfo.me website it keeps showing me that I am using the Firefox web browser, as Ponchale told me previously in another forum https://github.com/goastian/midori-desktop/issues/65 he had been doing tested with this option and did not have any problems, therefore, I do not know why this is happening to me in particular, I do not know if it is some internal error in my computer or what

PS: The good part is that I have also checked if the user.js options work that I had previously opened a thread talking specifically about it https://github.com/goastian/midori-desktop/issues/64 and it seems that they have indeed fixed that problem

### Reproduction Steps

Go to Settings
General
User Agent
Select any of the user agent options
Go to deviceinfo.me/ on this web page you can see that the configurations have not been applied

### Expected Behavior

The expected behavior in the Browser section of deviceinfo.me appears that I am using any of the other previously selected user agents instead of Firefox

### Actual Behavior

When I try to spoof the web browser user agent I can't do it

### Screenshots

https://github.com/goastian/midori-desktop/assets/126993006/d4bbff66-d1c1-40a4-b8dc-f305d522d09a

### Browser Version

Windows 11 Pro 23H2

### Operating System

11.3.0 (64-bit)

**Comment by Ponchale** [comment]
please update to Midori 11.3.1

**Comment by MuerteRoja** [comment]
> please update to Midori 11.3.1

https://github.com/goastian/midori-desktop/assets/126993006/1b0c2729-0eea-43ea-b42f-06dcbe4c6d38

**Comment by Ponchale** [comment]
https://github.com/goastian/midori-desktop/assets/285103/e3e12306-47b9-4ade-b30f-82730dbf5718

We will review this "incident" people did not trust said page because we know that this function is working perfectly in all our tests.

Even in two operating systems working, so I will proceed to close this problem since everything seems to be fine
