### ISSUE TITLE
[Bug]: Not all of the initial preferences set correctly

### ISSUE THREAD

**Issue by jamesbond3142** [goastian/midori-desktop#75]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Some of the initial preferences are not set, due to javascript error in 000-floorp.js

### Reproduction Steps

1. Clear all the existing profiles and caches (=install as new).
2. Launch browser from terminal
3. See the error

### Expected Behavior

The preferences should be applied, and there should be no error.

### Actual Behavior

As reported

### Screenshots

Console output:

```
defaults/preferences/000-floorp.js:123: prefs parse error: expected ';' after ')'
```

### Browser Version

11.3.3

### Operating System

Fatdog64 Linux

### Additional Context

First noticed in 11.3.2.

**Comment by Ponchale** [comment]
Please see the new update this and other issues have been fixed.
