### ISSUE TITLE
[Bug]: OpenH264 codec not installed

### ISSUE THREAD

**Issue by jamesbond3142** [goastian/midori-desktop#76]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

All Firefox-based browsers will attempt to download and use OpenH264 plugin when they're first launched, for compatibility reasons. Midori used to do this as well, but since 11.3, it failed to to do that. 

### Reproduction Steps

1. Remove all profiles and cache (=install as new). This is important, because if a profile created by Midori 11.2 is used, then the bug is masked (not visible).
2. Launch Midori
3. Check the plugins state in about:plugins

### Expected Behavior

The OpenH264 codec plugin is downloaded and used.

### Actual Behavior

The OpenH264 codec plugin is never downloaded. 

### Screenshots

Midori actually tries to download the plugin, but it fails with the following errors:

Console output:
```
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/GMPInstallManager.sys.mjs, line 353: ReferenceError: trustedContentSignatureRoot is not defined
JavaScript error: resource://gre/modules/GMPInstallManager.sys.mjs, line 353: ReferenceError: trustedContentSignatureRoot is not defined
```

### Browser Version

11.3.3

### Operating System

Fatdog64 Linux

### Additional Context

The bug was seen in 11.3.2 and 11.3.3.
Midori version 11.2 works well and do not exhibit this bug.

**Comment by Ponchale** [comment]
Please see the new update, we have fixed this and other bugs. Reopen if necessary.

**Comment by doglinux** [comment]
It's good now, thanks !
