### ISSUE TITLE
[Bug]: Workspaces dissappear after rebooting Midori 11.3.3

### ISSUE THREAD

**Issue by francjp** [goastian/midori-desktop#77]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

As mentioned on issue #63 
When I have a session initiated with 2 or more workspaces, the names and the workspaces dissappear once the browser is re-started. I've tried with and without any addon, with a complete new profile, on a new installation, etc. This didn't happened on 11.3.2, and it's an issue that I've detected since the new release.

For many of us that uses this browser with several tabs open, this is a major bug ;)

### Reproduction Steps

1. Open Midori
2. Create one or more workspaces, rename them or leave it by default
3. Place some tabs on each workspace (doesn't matter if you move tabs from one space to another, or simply open new tabs)
4. Close Midori
5. Re-open Midori, look for Workspaces, and all are gone, except for the "Default" one

### Expected Behavior

Once I reopen the browser, I'm expecting to have each tab on their different workspace

### Actual Behavior

I need to create workspaces from scratch, and move the tabs inside again.

### Screenshots

No need for screenshot

### Browser Version

11.3.3

### Operating System

Linux (Manjaro) - Tar.bz package version

### Additional Context

This happened with the .tar.bz package, and also with the package from the official repositories through the updater on Manjaro (AUR repos)

**Comment by Ponchale** [comment]
This problem has been solved in version 11.3.4 and is now available in the latest commits
