### ISSUE TITLE
[Bug]: 11.3.3 uninstallable on Ubuntu Noble

### ISSUE THREAD

**Issue by eris23** [goastian/midori-desktop#78]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

[Bug]: 11.3.3 uninstallable on Ubuntu Noble

 midori : Depends: libvpx7 but it is not installable or
                   libvpx6 but it is not installable or
                   libvpx5 but it is not installable

noble has libvpx9

### Reproduction Steps

1. Try to install
2. dpkg: dependency problems prevent configuration of midori:
 midori depends on libvpx7 | libvpx6 | libvpx5; however:
  Package libvpx7 is not installed.
  Package libvpx6 is not installed.
  Package libvpx5 is not installed.

### Expected Behavior

1. Try to install
2. Installs

### Actual Behavior

1. Try to install
2. dpkg: dependency problems prevent configuration of midori:
 midori depends on libvpx7 | libvpx6 | libvpx5; however:
  Package libvpx7 is not installed.
  Package libvpx6 is not installed.
  Package libvpx5 is not installed.

### Screenshots

n.a.

### Browser Version

11.3.3

### Operating System

Kubuntu 24.04

**Comment by abejaranoh** [comment]
reproduced on docker ubuntu:noble

`apt update`
`apt install wget`
`wget -O /etc/apt/trusted.gpg.d/midori-archive-keyring.gpg http://repo.astian.org/midori-archive-keyring.gpg`
`echo "deb http://repo.astian.org midori main" | tee /etc/apt/sources.list.d/midori.list`
`apt update`
`apt install midori`


root@3650d7c1d7ee:/# apt install midori
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 midori : Depends: libvpx7 but it is not installable or
                   libvpx6 but it is not installable or
                   libvpx5 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by josejp2424** [comment]
eso se soluciona reempaquetando midori, que no tenga encuenta esas librerias.

**Comment by Ponchale** [comment]
> eso se soluciona reempaquetando midori, que no tenga encuenta esas librerias.

Este problema se ha resuelto en la version 11.3.4 generando nuevos paquetes, en el lanzamiento quedara solucionado.
