### ISSUE TITLE
[Bug]: Link destination preview disappears

### ISSUE THREAD

**Issue by meypi** [goastian/midori-desktop#79]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The link destination ( URL ) no longer appears when you hover over a link after opening a web panel and closing it again in the sidebar.

### Reproduction Steps

1. Start midori.
2. Hover over a link in the browser window, for example a site on the midori new tab page, the url should appear in the bottom left corner. Ok.
3. Open a web panel ( in the sidebar ), for example https://notes.astian.org, which is pinned by default and close it again by clicking the same web panel icon again.
4. Hover over a link again, the destination of the link ( URL ) should now no longer appear in the bottom left corner.

### Expected Behavior

Show link destination when hovering over a link.

### Actual Behavior

Link destination is not shown.

### Screenshots

![midori_report](https://github.com/goastian/midori-desktop/assets/99614822/d0a17d87-5fae-4264-891c-1fea47961d1d)

### Browser Version

Midori Desktop 11.3.3 (64-bit)

### Operating System

Edition	Windows 11 Home Version	23H2 OS build	22631.3593 Experience	Windows Feature Experience Pack 1000.22700.1003.0

**Comment by Ponchale** [comment]
This issue has been resolved in version 11.4 please update in the repo this applications and packages for each operating system.
