### ISSUE TITLE
[Bug]: "Display Tab Bar underneath the Toolbar" doesn't save setting after browser restarted

### ISSUE THREAD

**Issue by audio101** [goastian/midori-desktop#80]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After browser is restarted or new browser loaded, if "Display Tab Bar underneath the Toolbar" Design setting is selected, the setting does not save & reverts to "Default" radio button & Tab Bar position.

### Reproduction Steps

1. Select "Display Tab Bar underneath the Toolbar".
2. Close/restart browser.
3. Observe tab(s) positioning change from previously underneath address bar, to above the address bar (default).
4. Observe settings radio button change: "Design" > "Tab Bar" > "Default"

### Expected Behavior

"Display Tab Bar underneath the Toolbar" setting should always save tab setting despite restarting/reloading the browser.

### Actual Behavior

"Display Tab Bar underneath the Toolbar" does not save tab setting.

### Screenshots

![underneath toolbar](https://github.com/goastian/midori-desktop/assets/90048453/f9c037a6-9793-40ea-81f3-ab51fa9fced3)
![default](https://github.com/goastian/midori-desktop/assets/90048453/0e73d919-8e0f-4448-8100-3d3b7c03bba9)

### Browser Version

v11.3.3 (AUR: midori-bin 11.3.3-1)

### Operating System

Manjaro Linux XFCE

**Comment by Ponchale** [comment]
Fix problem
