### ISSUE TITLE
[Bug]: in run "sudo apt install ./midori_11.4_amd64.deb  -y"

### ISSUE THREAD

**Issue by MiguelSanzBr** [goastian/midori-desktop#84]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Note, a seleccionar 'midori' em vez de './midori_11.4_amd64.deb'
Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 midori : Depende: libc6 (>= 2.36) mas 2.35-0ubuntu3.8 está para ser instalado
          Depende: libvpx7 (>= 1.12.0) mas 1.11.0-2ubuntu2.3 está para ser instalado
          Depende: libx11-xcb1 (>= 2:1.8.4) mas 2:1.7.5-1ubuntu0.3 está para ser instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.

### Reproduction Steps

sudo apt install ./midori_11.4_amd64.deb  -y

### Expected Behavior

midori 11.4 works

### Actual Behavior

no

### Screenshots

no

### Browser Version

11.4

### Operating System

Linux Mint cinnamon

**Comment by abejaranoh** [comment]
**Reproduced on Ubuntu 24.04 on Docker**

**Steps:**
    apt update
    apt install wget 
    wget https://github.com/goastian/midori-desktop/releases/download/v11.4/midori_11.4_amd64.deb
    apt install ./midori_11.4_amd64.deb

**Result:**
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'midori' instead of './midori_11.4_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 midori : Depends: libvpx7 (>= 1.12.0) but it is not installable
          Recommends: libavcodec60 or
                      libavcodec-extra60 but it is not going to be installed or
                      libavcodec59 but it is not installable or
                      libavcodec-extra59 but it is not installable or
                      libavcodec58 but it is not installable or
                      libavcodec-extra58 but it is not installable or
                      libavcodec57 but it is not installable or
                      libavcodec-extra57 but it is not installable or
                      libavcodec56 but it is not installable or
                      libavcodec-extra56 but it is not installable or
                      libavcodec55 but it is not installable or
                      libavcodec-extra55 but it is not installable or
                      libavcodec54 but it is not installable or
                      libavcodec-extra54 but it is not installable or
                      libavcodec53 but it is not installable or
                      libavcodec-extra53 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Ponchale** [comment]
This problem is due to the packaging process for Ubuntu/Debian our colleague josejp2424 is working on this. 

Thanks for the Thanks for the report.

**Comment by Ponchale** [comment]
fix problem in the package .deb
