### ISSUE TITLE
[Bug]: Midori opens on the first desktop even when initiated on a different virtual desktop on Windows

### ISSUE THREAD

**Issue by gochaavsajanishvili** [goastian/midori-desktop#91]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When I launch Midori on a secondary virtual desktop on Windows, it opens on the first desktop instead of the intended one. If I open it a second time, Midori then correctly appears on the second desktop, resulting in two instances — one on the first desktop and another on the second. I have to manually close the instance on the first desktop each time to avoid duplicates.

### Reproduction Steps

1. Open a second virtual desktop on Windows using Task View (Win + Tab).
2. Launch Midori on the second virtual desktop.
3. Observe that Midori flashes, opens and "jumps" to the first desktop and  instead of staying on the second.
4. Open Midori again on the second desktop to work around this issue. A second instance appears, this time on the correct desktop.
5. Manually close the instance on the first desktop to continue using Midori only on the second desktop.

### Expected Behavior

Midori should open on the virtual desktop where it was launched, without needing a second launch or manual closing of duplicate instances.

### Actual Behavior

Midori always opens on the first desktop initially, regardless of where it was launched. A second launch is required to open it on the intended desktop, resulting in duplicate instances.

### Screenshots

https://github.com/user-attachments/assets/6d9a1afd-be97-453a-aa4d-795abed420d5

### Browser Version

midori-11.3.3.win64

### Operating System

Edition: Windows 11 Pro Version: 23H2 OS Build: 22631.4391

### Additional Context

- I have ensured that I am using the latest version of Midori, as downloaded from the [official website](https://astian.org/midori-browser/windows/).

- I have attempted other workarounds, such as moving the window through Task View and "Shows this on all desktops" feature.

- This behavior does not occur with other browsers or applications, so it seems specific to Midori’s interaction with Windows’ virtual desktop system.

**Comment by Ponchale** [comment]
We recommend you to migrate to version 11.4 which has been available for weeks in our repository.
https://github.com/goastian/midori-desktop/releases/tag/v11.4

**Comment by gochaavsajanishvili** [comment]
> We recommend you to migrate to version 11.4 which has been available for weeks in our repository. https://github.com/goastian/midori-desktop/releases/tag/v11.4

It did work, thanks.
